//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhom
    {
        public int maDeTai { get; set; }
        public int MSSV { get; set; }
        public int id { get; set; }
    
        public virtual DeTai DeTai { get; set; }
    }
}
